cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'ansible'
brew 'assh'
brew 'coreutils'
brew 'curl'
brew 'go'
brew 'grc'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'imagemagick'
brew 'md5sha1sum'
brew 'libgit2'
brew 'openssl'
brew 'mas'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'python'
brew 'tmate'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

brew 'homebrew/completions/brew-cask-completion'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/make'
brew 'homebrew/dupes/ncurses'
brew 'homebrew/dupes/nano'
brew 'homebrew/dupes/unzip'
brew 'homebrew/dupes/whois'
brew 'homebrew/php/php71'
brew 'homebrew/php/php71-imagick'
brew 'homebrew/php/php71-xdebug'
brew 'homebrew/php/php71-opcache'

cask '1password'
cask 'cleanmymac'
cask 'dropbox'
cask 'firefox'
cask 'franz'
cask 'google-chrome'
cask 'google-drive'
cask 'gpgtools'
cask 'phpstorm'
cask 'poedit'
cask 'sequel-pro'
cask 'slack'
cask 'skype'
cask 'sublime-text'
cask 'transmit'
cask 'tower'
cask 'quicklook-json'
cask 'qlmarkdown'
cask 'qlcolorcode'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'keybase'
cask 'macdown'

mas 'Xcode', id: 497799835
mas 'Harvest', id: 506189836
