cask_args appdir: '/Applications'

tap 'homebrew/cask-cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ansible'
brew 'assh'
brew 'coreutils'
brew 'composer'
brew 'curl'
brew 'go'
brew 'grc'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'mas'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'python'
brew 'tmate'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'php72'

cask '1password'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'visual-studio-code'
cask 'poedit'
cask 'sequel-pro'
cask 'setapp'
cask 'slack'
cask 'skype'
cask 'sublime-text'
cask 'transmit'
cask 'tower'
cask 'quicklook-json'
cask 'qlmarkdown'
cask 'qlcolorcode'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'macdown'
cask 'spotify'
cask 'notion'
cask 'adobe-creative-cloud'
cask 'harvest'
cask 'chatmate-for-whatsapp'
cask 'qbittorrent'

mas 'Xcode', id: 497799835
